server:
  port: 8180

spring:
  application:
    name: seata-order-service
  cloud:
    alibaba:
      seata:
        tx-service-group: fsp_tx_group
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: 123456
    url: jdbc:mysql://localhost:3306/seata-order
    username: root

# 关闭熔断器配置
feign:
  hystrix:
    enabled: false

# 可以配置日志路径下的打印方式，根据包名来
logging:
  level:
    com:
      seata: info

# mybaits
mybatis:
  mapperLocations: classpath:mapper/*.xml
